version: '3'

services:
  playerwalletservice:
    image: playerwalletservice:latest
    ports:
      - 8080:8080
  gameplayclient:
    image: gameplayclient:latest
    environment:
      - PLAYERWALLETSERVICE_HOSTNAME=playerwalletservice